def notes(amount):
    if(amount>2000):
        twoth=amount//2000
        print("2000->",twoth,"note")
        amount-=2000
    if(amount>500):
        fivehund=amount//500
        print("500->",fivehund,"note")
        amount-=500
    if(amount>=200):
        twohund=amount//200
        print("200->",twohund,"note")
        amount-=200
    if(amount>=100):
        hund=amount//100
        print("100->",hund,"note")
        amount-=100
    if(amount>=50):
        fif=amount//50
        print("50->",fif,"note")
        amount-=50
    if(amount>=20):
        twe=amount//20
        print("20->",twe,"note")
        amount-=20
    if(amount>=10):
        ten=amount//10
        print("10->",ten,"note")
        amount-=10
    if(amount>=2):
        two=amount//2
        print("2->",two,"note")
        amount-=2
    if(amount==1):
        one=amount
        print("1->",one,"note")
notes(2678)